/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cbt;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Quiz
     */
    public int rollno;
    public int marks = 0;
    public int qid = 1;
    ResultSet rs ;
    DbManager dm;
    public String ans;
    public Quiz() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize(); // widht and height
        // size.width = screen width
        // getWidth() = main form width
        // size.height = screen height
        //getHeight() =  main form ki widht
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
    }
    // method for check ans is write or not
    public void check()
    { //  check method begin
    String resans ="";
    if (opt1.isSelected()) // agar option one select kiya gya hai
    {
    resans = opt1.getText(); // option will be store in this 
    }
    else if(opt2.isSelected()){
    resans  = opt2.getText();
    }
    else if(opt3.isSelected()) {
    resans  = opt3.getText();
    }
    else if(opt4.isSelected()) {
    resans  = opt4.getText();
    }
    if (resans.endsWith(ans))
    {
    marks = marks+1;
    }
    } //  check method end
    
    public Quiz(int rno)
    { // contructor for roll begin
        initComponents();
        rollno  =rno;
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize(); // widht and height
        // size.width = screen width
        // getWidth() = main form width
        // size.height = screen height
        //getHeight() =  main form ki widht
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        ButtonGroup bg  = new ButtonGroup();
        bg.add(opt1);
        bg.add(opt2);
        bg.add(opt3);
        bg.add(opt4);
        btnSubmit.setEnabled(false); //  submit to  false kr dge until all question get done
        dm = new DbManager();
        rs  = dm.select("select * from qb where id = '"+qid+"'"); //  i.e fist question access
        try {
            if (rs.next()){
        lblId.setText(rs.getString("id"));
        lblQuestion.setText(rs.getString("question"));
        opt1.setText(rs.getString("opt1"));
        opt2.setText(rs.getString("opt2"));
        opt3.setText(rs.getString("opt3"));
        opt4.setText(rs.getString("opt4"));
        ans  = rs.getString("ans"); //  answer rec 
        qid =qid+1;   //  question increase 
            }
        }// try end
        catch (SQLException ex)
        {
        ex. printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CBT");
        setBackground(new java.awt.Color(153, 204, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Attempt Quiz");

        lblId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblId.setText("id");

        lblQuestion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQuestion.setText("Question");

        opt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        opt1.setText("Option1");

        opt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        opt2.setText("Option2");

        opt3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        opt3.setText("Option3");

        opt4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        opt4.setText("Option4");

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(0, 51, 102));
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(0, 51, 102));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opt1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(opt2)
                            .addComponent(opt3)
                            .addComponent(opt4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnNext)
                        .addGap(83, 83, 83)
                        .addComponent(btnSubmit)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(opt1)
                .addGap(18, 18, 18)
                .addComponent(opt2)
                .addGap(18, 18, 18)
                .addComponent(opt3)
                .addGap(18, 18, 18)
                .addComponent(opt4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnSubmit))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        check();
        rs  = dm.select("select * from qb where id = '"+qid+"'"); //  i.e fist question access
        try {
            if (rs.next()){
        lblId.setText(rs.getString("id"));
        lblQuestion.setText(rs.getString("question"));
        opt1.setText(rs.getString("opt1"));
        opt2.setText(rs.getString("opt2"));
        opt3.setText(rs.getString("opt3"));
        opt4.setText(rs.getString("opt4"));
        ans  = rs.getString("ans"); //  answer rec 
        qid =qid+1;   //  question increase 
            }
            else {
            btnSubmit.setEnabled(true);
            }
        }// try end
        catch (SQLException ex)
        {
        ex. printStackTrace();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        //rollno k aadhar pr student ki detail find krge 
        rs= dm.select("select * from student where rollno = '"+rollno+"'");
        try
        {// try begin
        if (rs.next())
        { // outer if begin
        String name = rs.getString("name");
        String branch = rs.getString("branch");
        String year = rs.getString("year");
        String query = "insert into result(rollno, name, branch, year, marks)values('"+rollno+"','"+name+"','"+branch+"','"+year+"','"+marks+"')";
        boolean res = dm.insertUpdateDelete(query);
        if (res == true)
        { //  inner if begin
        JOptionPane.showMessageDialog(this, "success your marks = " + marks);
        } //  inner if end 
        else 
        { //  else inner begin
              JOptionPane.showMessageDialog(this, "not submitted but your marks = " + marks);
        }  //  else inner end
        this.setVisible(false);
        new MainForm().setVisible(true);
        }// outer if end 
        } // try end
        catch(SQLException ex)
        { // catch begin
        ex .printStackTrace();
        } // cathch end 
       // JOptionPane.showMessageDialog(this, "you secured marks = "+ marks);
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    // End of variables declaration//GEN-END:variables
}
